### ISSUE TITLE
The ToolTip Hidden Divs Reinit After Ajax Loads

### ISSUE THREAD

**Issue by sadeghbarati** [prevwong/drooltip.js#2]
![screenshot 9](https://user-images.githubusercontent.com/17789047/32456783-0e864736-c33c-11e7-9e4c-74f0f076e6b5.png)

Hey Man Thank You For Your Awsome Plugin My Qustion Is
Plugin Create Some Thing Like This For Example
`.myTooltip_0 To .myTooltip_10` 
Im Using Ajax For Load New Content And New HTML File
But After Load New HTML File Again Those Divs Are added Again like this
`.myTooltip_0 To .myTooltip_10` And Again Start form `.myTooltip_0 To .myTooltip_10`

Another Issue I Wana Help is, Hovering  Tooltips Inside of container when hover each tooltip in the container all of them will be shown and when Mouse Cursor Get out of container tooltips hides

How To Fixed These Issues??

Thanks ^_^

**Comment by prevwong** [comment]
Hey there, thanks for posting! Mind sharing your AJAX script ? 

But from what I can observe in your screenshots, I assume when you perform your AJAX call, you're loading the entire content of the destination page which perhaps also contains the same script(s) used to initiate the Drooltip instances, hence is why the tooltips are being re-added again.

As of now, Drooltip does not have a destroy() method to remove all the added tooltips associated with an instance (but I might add this in a future update 😄 ). Meanwhile, if what I said is the case, you can manually remove all the `.drooltip` elements during your AJAX call prior to loading the new HTML page.

Regarding your 2nd issue, I am not quite sure if I understand correctly, could you please elaborate further on what you mean ? 

Cheers!
